### ISSUE TITLE
Update "Contributing to RackHD" Section

### ISSUE THREAD

**Issue by bossidy** [RackHD/docs#195]
Add updated content from https://github.com/RackHD/specs/blob/master/README.md

**Comment by bossidy** [comment]
And might refer to https://github.com/emccode/emccode.github.io/wiki/How-to-contribute-to-EMC-CODE-projects

**Comment by heckj** [comment]
We've got slightly different contribution rules - we've leveraged their stuff, but it's not the same I'm afraid

**Comment by bossidy** [comment]
OK, I should've thought of that....

**Comment by heckj** [comment]
Related, got some feedback from @kacole2 on using our existing contrib docs, even direct from that README:

**[kacole2]:**
don’t take any of this the hard way. I’m tying to immerse myself in this for the past 24 hours and i’m having a hard time grasping what I can do with the Vagrant Monorail piece outside of the sample given.
1) I can’t login to the CoreOS box, so I don’t know what un/pw combo is given. The `task` in the library shows `root/root` but that doesn’t work. And I can’t use SSH because I didn’t provide a cloud-config. 
2) the example doesn’t show a cloud-config, therefor 1 can’t be completed. Does the cloud-config need to be transferred to the monorail host? can it be pulled from a network location?
3) No clear direction on using `properties` or `options` for tasks in a graph. Do they overwrite the default in the `task` in the library?
4) I sifted through all the tasks and workflows in the library, but most of those can't be used OOB (hence my Ubuntu installation question earlier). perhaps just Node Reboot, Send Finish Trigger, Power Off Node, etc. not sure what else I can do that’s valuable.
5) no idea what `noop` means and I’m seeing it in a few places.
6) no direction on easily getting another OS stood up (related to 4)
7) I tried making my own graph by changing properties and adding different tasks but they have all failed because of reasons stated above.


**[heckj]:**
no issue on this side, seriously looking for how to continue to make it better and where we’re missing. We’ve been in the forest so long we’re not always seeing the trees, totally need to lean on an outside perspective here. Appreciate the details!

So two immediate take-aways:

​1) make it more clear and obvious in our docs or readme that to install alternative OS’s, you’ll need to get and unpack the OS installation ISOs
2) somewhere we should explain the OS install, since that’s clearly the easiest first win - and point to what it’s doing, including that there’s templates and profiles. Those aren’t updatable via API calls today, but are via dropping in files. How to make your own “OS install” process is likely going to be a super-common immediate request
And beyond that, we ​*are*​ crippled to some extent due to the Vagrant setup /not/ having out-of-band-management controls, so using many of the other workflows needs to be explained (that you start it, and have to manually reset the VM) or at least call it out until we can get the vBMC stuff open sourced from our Shanghai bretheren

**[kacole2]:**
exactly. we just have to think about it from a first-time user perspective… the Vagrant Monorail is going to be good for a few things:
1) everyone WILL USE THIS FIRST. always. No one is going to do a full-blown RackHD deployment on their infrastructure without testing the Vagrant setup first
2) Once someone runs through the first sample, they will want to hack around with it to see what else it can do. (pretty much what I was going for)
3) the vagrant setup will be pretty good for a testing/development environment. This is where users will  try their graphs before pushing it to their physical racks.(edited)

so i do believe you are right when you say that different OS installs are the easy win. It will get everyone familiar with the syntax and process of RackHD without having to do a full-blown deployment. The Vagrant piece, IMO, is crucial to the first impression. If someone fires up Vagrant and then says “so what?” or “what am i supposed to do next?” there isn’t much incentive for them to dive further.

**Comment by heckj** [comment]
@bossidy I'm going to continue to grow the content in https://github.com/rackhd/rackhd/tree/master/example - maybe instead of porting the content, it would make sense to reference this document in http://localhost:8000/getting_started.html
